baseURL = 'https://busseig.abellot.net/'
languageCode = 'ca'
title = 'sóc Balena'
theme = 'PaperMod'
defaultContentLanguage = 'en'
buildFuture = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  post = "/post/:slug/"

[Params]
    subtitle = "Afició al busseig recreatiu lent..."
    logo = "img/socbalenacua.png"
    mainSections = ["post","posts"]

paginate = 10

#
# Defineixo el menú superior.
#
[[menu.main]]
    name = "Articles del blog"
    url = "/page/totselsposts/"
    weight = 1

[[menu.main]]
    name = "Punts d'Immersió"
    url = "/page/puntsimmersio/"
    weight = 2

[[menu.main]]
    name = "Galeria Fotogràfica"
    url = "/page/galeriafotos/"
    weight = 3

[[menu.main]]
    name = "Diari Busseig"
    url = "https://sb-diaribusseig.abellot.net"
    weight = 4

[[menu.main]]
    name = "Enllaços"
    url = "/page/links/"
    weight = 5

[[menu.main]]
    name = "Contacte"
    url = "/page/contacte/"
    weight = 6